# General Settings
set preview_images true
set preview_images_method ueberzug
set line_numbers relative
set mouse_enabled false
default_linemode devicons

# Movement
## Map
# map gA cd /mnt/external-hdd/kuda/Videos/Anime
map gd cd ~/Documents/
map gD cd ~/Downloads/
map gc cd ~/.config/
map gC cd ~/.cache/
# map ga cd ~/Videos/Anime/
# map gm cd ~/Manga
map gp cd ~/Pictures/
# map gr cd ~/.config/ranger/
# map gs cd ~/.local/bin/
# map gT cd ~/.local/share/Trash
map gl cd ~/.local/
map gV cd ~/Videos
## Unmap
unmap gL
unmap gm
unmap gs
unmap go
unmap gr
unmap g?

# Create {item}
map nD console mkdir%space
map nF console touch%space
map dT shell trash-put %s
