#################################
#           Backend             #
#################################
backend = "glx";
# Enable for tear-free video; disable if you feel input lag or "heavy" windows
vsync = true;

#################################
#          Performance          #
#################################
# For NVIDIA stutter; prevents extra processing overhead from dithering
dithered-present = false;
# Reduces CPU/GPU load by only redrawing changed areas
# Keep true, otherwise face massive CPU spikes
use-damage = true;
# Disable this if there is tearing, but will often fix "choppy" video
# When "true", reduces potential stuttering or CPU overhead
# I've noticed my screen flashes white when spawning windows if set to true, keep false
no-frame-pacing = false;
# Fixes NVIDIA-specific "ghosting" or partial redraws during workspace switches
xrender-sync-fence = true;
# Forces the GPU to finish the frame before showing it
use-glfinish = false;
# Unredirect all windows if a full-screen opaque window is detected.
# Noticable screentearing/artifacts in MPV when enabled. Disabled for now.
# unredir-if-possible = true;
# Delay before unredirecting the window, in milliseconds.
# unredir-if-possible-delay = 2000;
# Prevents showing the window until it's fully rendered

#################################
#       Window Grouping         #
#################################
# These group sub-windows (popups, menus) with their parent app.
# Helps with focus consistency and reduces overhead for apps like Discord.
detect-transient = true;
detect-client-leader = true;
detect-client-opacity = true;

#################################
#             Blur              #
#################################
# Dual-kawase is the most performant blur for Nvidia cards
# However... it takes a toll on your GPU (if it's old like mine lol)
 blur: {
  method = "dual_kawase";
  strength = 2;      # Adjust from 1 to 20 for more/less blur
  background = true;
  kern = "3x3box";
};

#################################
#        Fading/Shadow          #
#################################
# Set to false for instant window appearing/disappearing
fading = false;
# fade-in-step = 0.05;
# fade-out-step = 0.05;
# fade-delta = 4;
# no-fading-openclose = true; # Fixes workspace flash
shadow = false;

#################################
#           Corners             #
#################################
corner-radius = 0;

#################################
#           Rules               #
#################################
# To enable blur/transparency, uncomment kitty rule below
# Then, in kitty, set:
# background_opacity 0.8 (original 0.9)
# dynamic_background_opacity yes (yes for blur, no for none)
# rules = (
#     {
#         # Let kitty manage opacity
#          match = "class_g = 'kitty'";
#          opacity = 1.0;
#     },
#    {
#         match = "fullscreen";
#         blur-background = false;
#     },
#     {
#         match = "window_type = 'tooltip' || window_type = 'menu'";
#     }
# );
rules = (
    {
        # By default, disable blur for everything
        match = "window_type = 'any'";
        blur-background = false;
    },
    {
        # Stops the i3 'container' from flashing during workspace switches
        # or opening applications
        match = "class_g = 'i3-frame'";
        fade = false;
        opacity = 1.0;
    },
    {
        # If blur is enabled, remove it when right clicking in Zen
        match = "class_g = 'zen'";
        opacity = 1.0;
        blur-background = false;
    },
    {
        # Force these heavy apps to be 100% opaque to save CPU cycles
        match = "class_g = 'Spotify' || class_g = 'vesktop'";
        opacity = 1.0;
    },
    {
        # Let kitty handle its own transparency
        # Enable blur only for kitty terminal
        match = "class_g = 'kitty'";
        blur-background = true;
    }
);
